# Generated by Django 5.1.5 on 2026-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('replied', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('unsubscribed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Campaign daily stat',
                'verbose_name_plural': 'Campaign daily stats',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('scope', models.CharField(db_index=True, default='global', max_length=40)),
                ('key', models.CharField(db_index=True, max_length=60)),
                ('dimension', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Daily metric',
                'verbose_name_plural': 'Daily metrics',
                'ordering': ('-date', 'scope', 'key'),
            },
        ),
        migrations.CreateModel(
            name='ImportDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rows', models.PositiveBigIntegerField(default=0)),
                ('with_email', models.PositiveBigIntegerField(default=0)),
                ('without_email', models.PositiveBigIntegerField(default=0)),
                ('invalid_email', models.PositiveBigIntegerField(default=0)),
                ('duplicates', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import daily stat',
                'verbose_name_plural': 'Import daily stats',
                'ordering': ('-date',),
            },
        ),
    ]
