# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndailystat',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['key', 'date'], name='analytics_d_key_bd662c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(fields=('date', 'scope', 'key', 'dimension'), name='uniq_daily_metric'),
        ),
        migrations.AddField(
            model_name='importdailystat',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='imports.leadsource'),
        ),
        migrations.AddConstraint(
            model_name='campaigndailystat',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='uniq_campaign_daily'),
        ),
        migrations.AddConstraint(
            model_name='importdailystat',
            constraint=models.UniqueConstraint(fields=('source', 'date'), name='uniq_source_daily'),
        ),
    ]
