# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FOLLOW_UP', 'In follow-up'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Sequence completed')], db_index=True, default='PENDING', max_length=16)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_reason', models.CharField(blank=True, default='', max_length=200)),
                ('ai_generated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Campaign lead',
                'verbose_name_plural': 'Campaign leads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('value_proposition', models.TextField(blank=True, default='', help_text='One or two sentences used by the AI personalizer.')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text='Bullet list of pain points this service solves (feeds the AI).')),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceIndustryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = recommended first.')),
                ('reason', models.CharField(blank=True, default='', help_text='Why this service fits (shown to the AI and in the UI).', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service / industry mapping',
                'verbose_name_plural': 'Service / industry mappings',
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('target_states', models.JSONField(blank=True, default=list)),
                ('target_cities', models.JSONField(blank=True, default=list)),
                ('lead_ids', models.JSONField(blank=True, default=list, help_text='Explicitly selected leads (from the Lead Explorer).')),
                ('min_lead_score', models.PositiveIntegerField(default=0)),
                ('max_lead_score', models.PositiveIntegerField(default=0)),
                ('require_website', models.BooleanField(default=False)),
                ('require_phone', models.BooleanField(default=False)),
                ('require_contact_person', models.BooleanField(default=False)),
                ('exclude_replied', models.BooleanField(default=True)),
                ('exclude_ever_contacted', models.BooleanField(default=False)),
                ('exclude_missing_email', models.BooleanField(default=True)),
                ('use_ai_personalization', models.BooleanField(default=True)),
                ('ai_instructions', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('preview_text', models.CharField(blank=True, default='', max_length=300)),
                ('daily_limit', models.PositiveIntegerField(default=90)),
                ('send_window_start', models.CharField(blank=True, default='09:30', max_length=8)),
                ('send_window_end', models.CharField(blank=True, default='17:30', max_length=8)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('follow_up_enabled', models.BooleanField(default=True)),
                ('from_name', models.CharField(blank=True, default='', max_length=180)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('total_selected', models.PositiveIntegerField(default=0)),
                ('total_queued', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_replied', models.PositiveIntegerField(default=0)),
                ('total_bounced', models.PositiveIntegerField(default=0)),
                ('total_unsubscribed', models.PositiveIntegerField(default=0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ('-created_at',),
            },
        ),
    ]
