# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('companies', '0001_initial'),
        ('email_engine', '0001_initial'),
        ('imports', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='follow_up_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_engine.followupsequence'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='imports.leadsource'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_industries',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='companies.industry'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_sub_industries',
            field=models.ManyToManyField(blank=True, related_name='sub_industry_campaigns', to='companies.industry'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='email_engine.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='recommended_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campaigns.service'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recommended_service',
            field=models.ForeignKey(blank=True, help_text='Fixed service for this campaign (otherwise matched per lead).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.service'),
        ),
        migrations.AddField(
            model_name='serviceindustrymapping',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='companies.industry'),
        ),
        migrations.AddField(
            model_name='serviceindustrymapping',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_mappings', to='campaigns.service'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_887c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaigns_c_status_f2ab68_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['next_follow_up_at'], name='campaigns_c_next_fo_09ac13_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'lead'), name='uniq_campaign_lead'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_c_start_d_996cc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceindustrymapping',
            constraint=models.UniqueConstraint(fields=('industry', 'service'), name='uniq_industry_service'),
        ),
    ]
