# Generated by Django 5.1.5 on 2026-09-23 16:57

import apps.email_engine.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmailUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('transactional_count', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=90)),
                ('smtp_limit', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily email usage',
                'verbose_name_plural': 'Daily email usage',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FollowUpSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('stop_on_reply', models.BooleanField(default=True)),
                ('stop_on_bounce', models.BooleanField(default=True)),
                ('stop_on_unsubscribe', models.BooleanField(default=True)),
                ('stop_on_click', models.BooleanField(default=False)),
                ('stop_on_converted', models.BooleanField(default=True)),
                ('max_steps', models.PositiveIntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Follow-up sequence',
                'verbose_name_plural': 'Follow-up sequences',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('COLD_OUTREACH', 'Cold outreach'), ('FOLLOW_UP', 'Follow-up'), ('MEETING', 'Meeting request'), ('PROPOSAL', 'Proposal'), ('RE_ENGAGE', 'Re-engagement'), ('CUSTOM', 'Custom')], default='COLD_OUTREACH', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('preheader', models.CharField(blank=True, default='', max_length=300)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('uid', models.CharField(db_index=True, default=apps.email_engine.models.new_uid, max_length=64, unique=True)),
                ('unsubscribe_token', models.CharField(db_index=True, default=apps.email_engine.models.new_unsubscribe_token, max_length=64, unique=True)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('to_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=180)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=400)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped (quota/suppression)')], db_index=True, default='QUEUED', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=40)),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('recommended_service', models.CharField(blank=True, default='', max_length=180)),
                ('is_transactional', models.BooleanField(default=False, help_text='Transactional mail does not consume the marketing quota.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='campaigns.campaign')),
                ('campaign_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='campaigns.campaignlead')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='leads.lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='email_engine.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email message',
                'verbose_name_plural': 'Email messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FollowUpStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('delay_days', models.PositiveIntegerField(default=3)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('ALWAYS', 'Always'), ('NO_REPLY', 'No reply yet'), ('NO_OPEN', 'Not opened yet'), ('NO_CLICK', 'Not clicked yet')], default='NO_REPLY', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body_html', models.TextField(blank=True, default='')),
                ('use_ai', models.BooleanField(default=True)),
                ('ai_instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='email_engine.followupsequence')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_steps', to='email_engine.emailtemplate')),
            ],
            options={
                'verbose_name': 'Follow-up step',
                'verbose_name_plural': 'Follow-up steps',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed'), ('UNSUBSCRIBED', 'Unsubscribed'), ('COMPLAINT', 'Spam complaint'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('url', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_engine.emailmessage')),
            ],
            options={
                'verbose_name': 'Email event',
                'verbose_name_plural': 'Email events',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['message', 'type'], name='email_engin_message_8d4fb6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'scheduled_at'], name='email_engin_status_6cb15f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['campaign', 'status'], name='email_engin_campaig_59ce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['lead', 'created_at'], name='email_engin_lead_id_4efc10_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['to_email', 'created_at'], name='email_engin_to_emai_1e8d02_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['sent_at'], name='email_engin_sent_at_f3c81c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['step_number'], name='email_engin_step_nu_0fe861_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign_lead__isnull', False)), fields=('campaign_lead', 'step_number'), name='uniq_campaign_lead_step'),
        ),
        migrations.AddConstraint(
            model_name='followupstep',
            constraint=models.UniqueConstraint(fields=('sequence', 'order'), name='uniq_sequence_step'),
        ),
    ]
