# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed'), ('IMPORT_STARTED', 'Import started'), ('IMPORT_UPLOADED', 'Import file uploaded'), ('IMPORT_MAPPING_SAVED', 'Import mapping saved'), ('IMPORT_PROGRESS', 'Import progress'), ('IMPORT_COMPLETED', 'Import completed'), ('IMPORT_FAILED', 'Import failed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('LEAD_CREATED', 'Lead created'), ('LEAD_UPDATED', 'Lead updated'), ('LEAD_MERGED', 'Lead merged'), ('LEAD_SCORED', 'Lead rescored'), ('LEAD_STATUS_CHANGED', 'Lead status changed'), ('LEAD_SUPPRESSED', 'Lead suppressed'), ('LEAD_ENRICHED', 'Lead enriched'), ('CAMPAIGN_CREATED', 'Campaign created'), ('CAMPAIGN_UPDATED', 'Campaign updated'), ('CAMPAIGN_STARTED', 'Campaign started'), ('CAMPAIGN_PAUSED', 'Campaign paused'), ('CAMPAIGN_CANCELLED', 'Campaign cancelled'), ('CAMPAIGN_COMPLETED', 'Campaign completed'), ('EMAIL_QUEUED', 'Email queued'), ('EMAIL_SENT', 'Email sent'), ('EMAIL_FAILED', 'Email failed'), ('EMAIL_BOUNCED', 'Email bounced'), ('EMAIL_OPENED', 'Email opened'), ('EMAIL_CLICKED', 'Email clicked'), ('EMAIL_REPLIED', 'Email replied'), ('UNSUBSCRIBED', 'Unsubscribed'), ('QUOTA_REACHED', 'Daily quota reached'), ('CRM_STAGE_CHANGED', 'CRM stage changed'), ('AI_GENERATION', 'AI generation'), ('AI_FAILED', 'AI generation failed'), ('SETTINGS_UPDATED', 'Settings updated'), ('SUPPRESSION_ADDED', 'Suppression added'), ('SUPPRESSION_REMOVED', 'Suppression removed'), ('EXPORT', 'Data exported')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
    ]
