# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_normalized', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('email', models.CharField(blank=True, default='', max_length=320)),
                ('reason', models.CharField(choices=[('UNSUBSCRIBED', 'Unsubscribed'), ('BOUNCED', 'Bounced'), ('COMPLAINT', 'Spam complaint'), ('MANUAL_BLOCK', 'Manual block'), ('DO_NOT_CONTACT', 'Do not contact'), ('INVALID', 'Invalid address'), ('IMPORT', 'Imported suppression list')], db_index=True, default='MANUAL_BLOCK', max_length=24)),
                ('source', models.CharField(blank=True, default='MANUAL', help_text='UNSUBSCRIBE_LINK | BOUNCE_HANDLER | MANUAL | IMPORT | API', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions', to='email_engine.emailmessage')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Suppressed email',
                'verbose_name_plural': 'Suppressed emails',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SuppressionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_normalized', models.EmailField(db_index=True, max_length=320)),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('REMOVED', 'Removed'), ('REACTIVATED', 'Reactivated'), ('UPDATED', 'Updated')], default='ADDED', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suppression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='suppression.suppression')),
            ],
            options={
                'verbose_name': 'Suppression log',
                'verbose_name_plural': 'Suppression logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='suppression',
            index=models.Index(fields=['reason', 'is_active'], name='suppression_reason_e39ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='suppression',
            index=models.Index(fields=['created_at'], name='suppression_created_ae8f22_idx'),
        ),
    ]
