# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('full_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('seniority', models.CharField(blank=True, default='', max_length=60)),
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.CharField(blank=True, default='', max_length=320)),
                ('email_normalized', models.CharField(blank=True, db_index=True, default='', max_length=320)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('phone_type', models.CharField(blank=True, default='', help_text='Mobile / Landline / VOIP / Unknown (as provided by the source file)', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', max_length=64)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_decision_maker', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='imports.leadsource')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='imports.importfile')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['company', 'email_normalized'], name='contacts_co_company_ee3247_idx'), models.Index(fields=['email_normalized'], name='contacts_co_email_n_e27601_idx'), models.Index(fields=['phone_normalized'], name='contacts_co_phone_n_157405_idx'), models.Index(fields=['last_name', 'first_name'], name='contacts_co_last_na_bb56ce_idx')],
            },
        ),
    ]
