# Generated by Django 5.1.5 on 2026-09-23 16:57

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('rules', 'Rule-based (offline, no API key)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (local)')], max_length=32, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', apps.core.fields.EncryptedCharField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0.4)),
                ('max_tokens', models.PositiveIntegerField(default=700)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'AI provider',
                'verbose_name_plural': 'AI providers',
                'ordering': ('provider',),
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='rules', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('subject', models.CharField(blank=True, default='', max_length=400)),
                ('opening_sentence', models.TextField(blank=True, default='')),
                ('personalization', models.TextField(blank=True, default='')),
                ('value_proposition', models.TextField(blank=True, default='')),
                ('cta', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('recommended_service', models.CharField(blank=True, default='', max_length=180)),
                ('rationale', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('prompt', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('context_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected by safety check'), ('APPROVED', 'Approved')], db_index=True, default='PENDING', max_length=16)),
                ('safety_passed', models.BooleanField(default=True)),
                ('safety_notes', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI recommendation',
                'verbose_name_plural': 'AI recommendations',
                'ordering': ('-created_at',),
            },
        ),
    ]
