# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('name_normalized', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('legal_name', models.CharField(blank=True, default='', max_length=300)),
                ('dba_name', models.CharField(blank=True, default='', max_length=300)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('website_normalized', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=320)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('street_address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('zip_code', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_range', models.CharField(blank=True, default='', max_length=60)),
                ('annual_revenue', models.CharField(blank=True, default='', max_length=60)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('lead_count', models.PositiveIntegerField(default=0)),
                ('website_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='imports.leadsource')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='imports.importfile')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('absorbed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_into_log', to='companies.company')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_from', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company merge log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('full_path', models.CharField(blank=True, db_index=True, default='', max_length=400)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='companies.industry')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_companies', to='companies.industry'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['parent', 'name'], name='companies_i_parent__577852_idx'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_industry_parent_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name_normalized', 'domain'], name='companies_c_name_no_47d956_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry', 'state'], name='companies_c_industr_a6b395_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city', 'state'], name='companies_c_city_6d9404_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='companies_c_domain_99e280_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_c_created_301a54_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name_normalized', 'domain', 'city', 'state'), name='uniq_company_name_domain_place'),
        ),
    ]
