# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(db_index=True, max_length=300)),
                ('company_name_key', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('contact_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=320)),
                ('email_normalized', models.CharField(blank=True, db_index=True, default='', max_length=320)),
                ('email_status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('UNVERIFIED', 'Unverified'), ('RISKY', 'Risky'), ('BOUNCED', 'Bounced'), ('SUPPRESSED', 'Suppressed'), ('UNSUBSCRIBED', 'Unsubscribed')], db_index=True, default='MISSING', max_length=20)),
                ('email_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email_is_role', models.BooleanField(default=False)),
                ('email_is_free_provider', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('phone_type', models.CharField(blank=True, default='', max_length=32)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('website_normalized', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('website_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('website_accessible', models.BooleanField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('zip_code', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_range', models.CharField(blank=True, default='', max_length=60)),
                ('lead_status', models.CharField(choices=[('NEW', 'New'), ('IMPORTED', 'Imported'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('MISSING_EMAIL', 'Missing email'), ('DUPLICATE', 'Duplicate'), ('SUPPRESSED', 'Suppressed'), ('QUEUED', 'Queued'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('BOUNCED', 'Bounced'), ('UNSUBSCRIBED', 'Unsubscribed'), ('CONVERTED', 'Converted'), ('DO_NOT_CONTACT', 'Do not contact'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=24)),
                ('lead_score', models.IntegerField(db_index=True, default=0)),
                ('lead_quality', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('UNQUALIFIED', 'Unqualified')], db_index=True, default='COLD', max_length=16)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_category', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('source_city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('crm_stage', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('MEETING_REQUESTED', 'Meeting requested'), ('MEETING_SCHEDULED', 'Meeting scheduled'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('DO_NOT_CONTACT', 'Do not contact')], db_index=True, default='NEW', max_length=24)),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=400)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('times_contacted', models.PositiveIntegerField(default=0)),
                ('last_contacted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('do_not_contact', models.BooleanField(db_index=True, default=False)),
                ('enrichment_status', models.CharField(choices=[('NOT_PROCESSED', 'Not processed'), ('PROCESSING', 'Processing'), ('FOUND', 'Found'), ('NOT_FOUND', 'Not found'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (no website)')], db_index=True, default='NOT_PROCESSED', max_length=20)),
                ('enrichment_checked_at', models.DateTimeField(blank=True, null=True)),
                ('enrichment_data', models.JSONField(blank=True, default=dict)),
                ('enrichment_note', models.CharField(blank=True, default='', max_length=300)),
                ('ai_recommendation', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='contacts.contact')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='companies.industry')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='leads.lead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('recommended_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campaigns.service')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imports.leadsource')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imports.importfile')),
                ('sub_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_industry_leads', to='companies.industry')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.PositiveIntegerField(db_index=True, default=0)),
                ('method', models.CharField(choices=[('EMAIL', 'Same email'), ('COMPANY_WEBSITE', 'Company + website'), ('COMPANY_PHONE', 'Company + phone'), ('COMPANY_ADDRESS', 'Company + address'), ('COMPANY_CITY_STATE', 'Company + city + state'), ('COMPANY_NAME', 'Company name only')], max_length=24)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending review'), ('MERGED', 'Merged'), ('KEPT_BOTH', 'Kept both'), ('IGNORED', 'Ignored')], db_index=True, default='PENDING', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches', to='leads.lead')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='leads.lead')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead duplicate',
                'verbose_name_plural': 'Lead duplicates',
                'ordering': ('-confidence', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_name_key'], name='leads_lead_company_29f65d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email_normalized'], name='leads_lead_email_n_ddaf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['website_domain'], name='leads_lead_website_9128f7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_normalized'], name='leads_lead_phone_n_a5d917_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['industry', 'lead_score'], name='leads_lead_industr_7648ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sub_industry', 'lead_score'], name='leads_lead_sub_ind_049b22_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['state', 'city'], name='leads_lead_state_014db0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_status', 'email_status'], name='leads_lead_lead_st_4ff4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['crm_stage'], name='leads_lead_crm_sta_2b43ad_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='leads_lead_source__208d77_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at'], name='leads_lead_next_fo_ddbe21_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_duplicate', 'merged_into'], name='leads_lead_is_dupl_67b3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='leadduplicate',
            index=models.Index(fields=['resolution', 'confidence'], name='leads_leadd_resolut_eb1692_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicate',
            constraint=models.UniqueConstraint(fields=('lead', 'candidate'), name='uniq_duplicate_pair'),
        ),
    ]
