# Generated by Django 5.1.5 on 2026-09-23 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead note',
                'verbose_name_plural': 'Lead notes',
                'ordering': ('-is_pinned', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CRMActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('IMPORT', 'Imported'), ('EMAIL_QUEUED', 'Email queued'), ('EMAIL_SENT', 'Email sent'), ('EMAIL_OPENED', 'Email opened'), ('EMAIL_CLICKED', 'Email clicked'), ('EMAIL_FAILED', 'Email failed'), ('EMAIL_BOUNCED', 'Email bounced'), ('REPLY', 'Reply received'), ('UNSUBSCRIBED', 'Unsubscribed'), ('STAGE_CHANGE', 'Pipeline stage changed'), ('STATUS_CHANGE', 'Status changed'), ('MERGE', 'Merged'), ('CAMPAIGN_ADDED', 'Added to campaign'), ('CAMPAIGN_REMOVED', 'Removed from campaign'), ('AI_GENERATED', 'AI personalization'), ('CALL', 'Call'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('ENRICHMENT', 'Enrichment'), ('SUPPRESSION', 'Suppression')], db_index=True, default='NOTE', max_length=24)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_pinned', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'CRM activity',
                'verbose_name_plural': 'CRM activities',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['lead', 'occurred_at'], name='crm_crmacti_lead_id_ae4f3a_idx'), models.Index(fields=['type', 'occurred_at'], name='crm_crmacti_type_ad376d_idx')],
            },
        ),
    ]
