# Generated by Django 5.1.5 on 2026-09-23 16:57

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('secret_value', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('category', models.CharField(choices=[('email', 'Email & SMTP'), ('sending', 'Sending limits & schedule'), ('ai', 'AI'), ('scoring', 'Lead scoring'), ('dedupe', 'Deduplication'), ('imports', 'Imports'), ('crm', 'CRM'), ('compliance', 'Compliance & branding'), ('general', 'General')], db_index=True, default='general', max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_secret', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Safe to expose to the frontend (e.g. brand name).')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System setting',
                'verbose_name_plural': 'System settings',
                'ordering': ('category', 'key'),
            },
        ),
        migrations.CreateModel(
            name='SettingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('old_value', models.JSONField(blank=True, default=None, null=True)),
                ('new_value', models.JSONField(blank=True, default=None, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='system_settings.systemsetting')),
            ],
            options={
                'verbose_name': 'Setting change log',
                'verbose_name_plural': 'Setting change logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
