# Generated by Django 5.1.5 on 2026-09-23 16:57

import apps.imports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.imports.models.source_file_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel (.xlsx)'), ('XLS', 'Excel (.xls)')], default='CSV', max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('available_sheets', models.JSONField(blank=True, default=list)),
                ('has_header_row', models.BooleanField(default=True)),
                ('header_row_index', models.PositiveIntegerField(default=0)),
                ('detected_delimiter', models.CharField(blank=True, default=',', max_length=8)),
                ('detected_encoding', models.CharField(blank=True, default='utf-8', max_length=32)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('detected_mapping', models.JSONField(blank=True, default=dict)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('mapping_suggestions', models.JSONField(blank=True, default=list)),
                ('mapping_confirmed', models.BooleanField(default=False)),
                ('total_rows', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('ANALYZING', 'Analyzing'), ('READY', 'Ready for mapping'), ('MAPPED', 'Mapping confirmed'), ('IMPORTING', 'Importing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import file',
                'verbose_name_plural': 'Import files',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PARTIAL', 'Completed with errors')], db_index=True, default='PENDING', max_length=16)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveBigIntegerField(default=0)),
                ('processed_rows', models.PositiveBigIntegerField(default=0)),
                ('created_rows', models.PositiveBigIntegerField(default=0)),
                ('updated_rows', models.PositiveBigIntegerField(default=0)),
                ('skipped_rows', models.PositiveBigIntegerField(default=0)),
                ('duplicate_rows', models.PositiveBigIntegerField(default=0)),
                ('invalid_rows', models.PositiveBigIntegerField(default=0)),
                ('rows_with_email', models.PositiveBigIntegerField(default=0)),
                ('rows_without_email', models.PositiveBigIntegerField(default=0)),
                ('invalid_email_rows', models.PositiveBigIntegerField(default=0)),
                ('missing_company_rows', models.PositiveBigIntegerField(default=0)),
                ('error_rows', models.PositiveBigIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_batch', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='imports.importfile')),
            ],
            options={
                'verbose_name': 'Import job',
                'verbose_name_plural': 'Import jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveBigIntegerField(db_index=True)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], default='ERROR', max_length=12)),
                ('field', models.CharField(blank=True, default='', max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='imports.importjob')),
            ],
            options={
                'verbose_name': 'Import row error',
                'verbose_name_plural': 'Import row errors',
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='e.g. Public Contacts, Scraped, Purchased, Manual', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('industry_hint', models.CharField(blank=True, default='', max_length=180)),
                ('provider', models.CharField(blank=True, default='', max_length=180)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('total_rows', models.PositiveBigIntegerField(default=0)),
                ('valid_rows', models.PositiveBigIntegerField(default=0)),
                ('invalid_rows', models.PositiveBigIntegerField(default=0)),
                ('rows_with_email', models.PositiveBigIntegerField(default=0)),
                ('rows_without_email', models.PositiveBigIntegerField(default=0)),
                ('duplicate_rows', models.PositiveBigIntegerField(default=0)),
                ('invalid_emails', models.PositiveBigIntegerField(default=0)),
                ('missing_company_names', models.PositiveBigIntegerField(default=0)),
                ('imported_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead source',
                'verbose_name_plural': 'Lead sources',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='importfile',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='imports.leadsource'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='imports_imp_status_717e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['job', 'row_number'], name='imports_imp_job_id_7600e3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['category', 'created_at'], name='imports_lea_categor_3e10d5_idx'),
        ),
        migrations.AddIndex(
            model_name='importfile',
            index=models.Index(fields=['status', 'created_at'], name='imports_imp_status_1727d3_idx'),
        ),
    ]
